spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/demo
    username: mol
    password: toor
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
          dialect: org.hibernate.dialect.MariaDB103Dialect

server:
  compression:
    enabled: true
